### ISSUE TITLE
При индексировании не читаются автор, серия, жанр

### ISSUE THREAD

**Issue by vsuh** [egnd/fb2lib#5]
После запуска `build_index` и `build_summary`:

![image](https://user-images.githubusercontent.com/12156293/236180043-0213bcca-0183-4a6b-a902-551443e69533.png)

[Скрипт]()

**Comment by egnd** [comment]
Приложите пример файла книги

**Comment by vsuh** [comment]
[book.zip](https://github.com/egnd/fb2lib/files/11409592/book.zip)

**Comment by egnd** [comment]
Проверил на Вашей книге, вроде бы все работает:
![изображение](https://user-images.githubusercontent.com/31903154/236644298-65553b08-294f-4ec1-91a6-3587f514dac0.png)

В контейнере есть 3 entrypoint-а: 
1. build_index - строит поисковый индекс
2. build_summary - собирает суммарные показатели по текущему поисковому индексу (цифры в левом меню)
3. server - web-сервер как UI

Запускать эти команды нужно поочередно в описанном порядке. Перед первым шагом желательно почистить содержимое папок db и index, т.к. build_index пропускает проиндексированные ранее книги

**Comment by vsuh** [comment]
- Уточнил значения переменных, запустил индексирование
![image](https://user-images.githubusercontent.com/12156293/236902459-f322dc76-8ec3-4fda-ba02-76f421da4b68.png)
Судя по шуршанию винта и времени работы, индекс строится.
- Выполнил формирование summary
![image](https://user-images.githubusercontent.com/12156293/236902914-a073ddbb-3cae-4c58-baa8-c43902064134.png)
- запустил сервис
![image](https://user-images.githubusercontent.com/12156293/236903354-5cb98b59-0e73-4393-b133-2638f26c41ca.png)
- смотрю вебстраницу http://localhost:8040
![image](https://user-images.githubusercontent.com/12156293/236904070-165d08c3-6901-45ca-b24c-ada41096f9f7.png)

отлично!
