### ISSUE TITLE
Файл app.override.yml не описан

### ISSUE THREAD

**Issue by vsuh** [egnd/fb2lib#6]
Использованный в `Readme.md` файл `app.override.yml` непонятно как использовать.
Я попытался, взяв за шаблон файл [app.yml](https://github.com/egnd/fb2lib/blob/master/configs/app.yml), исправить значение номера порта и режима отладки, но после перезапуска контейнера параметры не изменились.

Файл `app.override.yml` можно как-то применить или он не должен использоваться?

**Comment by egnd** [comment]
Файл app.override.yml позволяет переопределять основной конфиг, как целиком так и по частям. Например, если добавить в такой файл:
```yaml
server:
  port: 8181
logs:
  debug: true
  pretty: true
  color: true
```
и смонтировать его в docker-compose.yml:
```yaml
volumes:
    - ./config.yml:/configs/app.override.yml:ro
```

то сервис внутри контейнера стартует на 8181 порту, вместе с цветным человекочитаемым форматом логов.

**Comment by vsuh** [comment]
Понятно, спасибо
